const sessions = [
  {
    sessionId: 1,
    mentorId: 4,
    menteeId: 5,
    sessionName: 'NodeJS',
    questions: 'Please I wanted to request for this session',
    menteeEmail: 'havuga@gmail.com',
    status: 'pending',
  },
  {
    sessionId: 2,
    mentorId: 3,
    menteeId: 5,
    sessionName: 'Laravel PHP',
    questions: 'Please I wanted to request for this session',
    menteeEmail: 'havuga@gmail.com',
    status: 'pending',
  },
  {
    sessionId: 3,
    mentorId: 3,
    menteeId: 5,
    sessionName: 'Java',
    questions: 'Please I wanted to request for this session',
    menteeEmail: 'havuga@gmail.com',
    status: 'rejected',
  },
  {
    sessionId: 4,
    mentorId: 3,
    menteeId: 5,
    sessionName: 'C++',
    questions: 'Please I wanted to request for this session',
    menteeEmail: 'havuga@gmail.com',
    status: 'accepted',
  },
  {
    sessionId: 5,
    mentorId: 3,
    menteeId: 2,
    sessionName: 'Ruby on Rails',
    questions: 'Please I wanted to request for this session',
    menteeEmail: 'hakiza@gmail.com',
    status: 'rejected',
  },
  {
    sessionId: 6,
    mentorId: 3,
    menteeId: 2,
    sessionName: 'Ruby',
    questions: 'Please I wanted to request for this session',
    menteeEmail: 'hakiza@gmail.com',
    status: 'accepted',
  },
  {
    sessionId: 7,
    mentorId: 3,
    menteeId: 2,
    sessionName: 'Ruby on',
    questions: 'Please I wanted to request for this session',
    menteeEmail: 'hakiza@gmail.com',
    status: 'pending',
  },
];

export default sessions;
